set imap_user = ''
set imap_pass = ''
set smtp_pass = ''
set use_from=yes
set smtp_url = 'smtps://user@domain.tld@imapserver.tld:465'
set realname = 'Mario Rossi'
set from = userfrom@domain.tld
set folder = 'imaps://imapserver.tld'
set spoolfile = "+INBOX"
set trash = "+Trash"
set record = "+Sent"
set signature = ~/.mutt/mail_signature
